name: "PlantUML diagram generator"
description: |
  Generate PlantUML diagrams with always up to date PlantUML (fork from holowinski)
author: "@timonback"

branding:
  icon: "bar-chart-2"
  color: "white"

inputs:
  args:
    description: "Arguments for PlantUML"
    required: true
    default: "-h"

runs:
  using: "docker"
  image: "docker://timonback/plantuml:1.2023.10"
  args:
    - ${{ inputs.args }}
